version: '3'
services:

  amc_dash_rest:
    # build:
    #   context: app
    #   dockerfile: Dockerfile
    container_name: amc_dash_rest
    image: cnccodecreater/amc_dash_rest:0.0.2
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_HOST_IP: "182.18.0.2"
      MONGODB_DATABASE: amcdb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
    depends_on: 
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - backend

  mongodb:
    # image: arm64v8/mongo
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    # command: mongod --auth
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: amcdb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      backend:
        ipv4_address: "182.18.0.2"

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "182.18.0.0/16"
          gateway: "182.18.0.1"

volumes:
  mongodbdata:
    driver: local